version: "3.9"
services:
  reverse-proxy:
    build: ./reverse-proxy
    environment:
      HTTPS: ${HTTPS}
      FRONTEND_DOMAIN_NAME: ${pilaon.com}
      BACKEND_DOMAIN_NAME: ${piloan.com}
      DOMAIN_VALIDATION_KEY: ${b8c25d38ac879024e4346bd0c3b37596f72ba6b599420b32c1e1200fbb5de0b64a0aa5a60728ad3a3bd2bc37cd29fecd3a9d86e380798edb437f2dbb8def5680}
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${DATA_DIRECTORY}/reverse-proxy/etc-letsencrypt:/etc/letsencrypt/

  frontend:
    build: ./frontend
    environment:
      BACKEND_URL: ${https://piloan.com}

  backend:
    build: ./backend
    environment:
      NODE_ENV: ${ENVIRONMENT}
      SESSION_SECRET: ${8552king_hosa}
      PI_API_KEY: ${nkgsp5bp8dz6jkhyccmmqmuoo05ilkbpm97gxhaxua9aljeqralcviuwjwrxa2a5}
      PLATFORM_API_URL: ${https://piloan.com}
      MONGO_HOST: mongo
      MONGODB_DATABASE_NAME: ${piloan}
      MONGODB_USERNAME: ${knnamdi1}
      MONGODB_PASSWORD: ${24thking$}
      FRONTEND_URL: ${https://www.piloan.com}

  mongo:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${knnamdi1}
      MONGO_INITDB_ROOT_PASSWORD: ${24thking$}
    ports:
      - 27027:27017
    volumes:
      - ${DATA_DIRECTORY}/mongo/data:/data/db
